### ISSUE TITLE
分页有问题

### ISSUE THREAD

**Issue by dongfangshen** [linezero/NETCoreBBS#3]
当显示第四页的时候，第一页与第二页之前有....

**Comment by linezero** [comment]
第一页和最后一页是一直展示。

**Comment by dongfangshen** [comment]
第一页与最后一页肯定是要一直展示的。你把pagesize调小一点，点到第四页看看，就明白了。当点到第四页时显示的为形如1]...[2][3][4]

**Comment by linezero** [comment]
这里优化一下。
