### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [linezero/NETCoreBBS#5]
Hello @linezero,

May I use some of this code inside my application, If I may would I need to provide any credits?

**Comment by linezero** [comment]
See [MIT License](https://github.com/linezero/NETCoreBBS/blob/master/LICENSE)

**Comment by ghost** [comment]
@linezero Thank you, stupid question but I'm new to this but I must contain your licence in my code if I use pieces of it correct?

**Comment by linezero** [comment]
Yes.
