### ISSUE TITLE
节点选择

### ISSUE THREAD

**Issue by Swift-T** [linezero/NETCoreBBS#7]
安装在本地了，可以注册用户和登陆，但是想发新帖要选节点但是没有任何选项。
还有数据库里没有内置的管理员账号，如何新建一个呢。貌似用户权限级别没有开发？
手动在数据库里新建topicnode 数据，也不能在发新帖的时候选择节点。点进节点可以在下面发新的帖子。
谢谢

**Comment by linezero** [comment]
二级节点才能选择，注册admin 即为管理员账号。
